services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\Core\Infrastructure\Behat\:
        resource: '../src/Core/Infrastructure/Behat/**/*'

    App\Activity\Domain\Repository\ActivityRepositoryInterface: '@App\Activity\Infrastructure\Repository\InMemoryActivityRepository'
    App\Order\Domain\Repository\OrderRepositoryInterface:       '@App\Order\Infrastructure\Repository\InMemoryOrderRepository'
    App\Payment\Domain\Repository\PaymentRepositoryInterface:   '@App\Payment\Infrastructure\Repository\InMemoryPaymentRepository'
    App\User\Domain\Repository\UserRepositoryInterface:         '@App\User\Infrastructure\Repository\InMemoryUserRepository'
    App\Voucher\Domain\Repository\VoucherRepositoryInterface:   '@App\Voucher\Infrastructure\Repository\InMemoryVoucherRepository'
    App\Entry\Domain\Repository\EntryRepositoryInterface:       '@App\Entry\Infrastructure\Repository\InMemoryEntryRepository'
