services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/**/*'
        exclude:
            - '../src/**/*/{*Controller.php,DependencyInjection,Model,Repository,Resources,Kernel.php}'
            - '../src/Core/*'

    App\Core\Infrastructure\Behat\:
        resource: '../src/Core/Infrastructure/Behat/**/*'

    DateTimeImmutable:
        class: \DateTimeImmutable
        
    App\Voucher\Domain\Repository\VoucherRepositoryInterface:
        class: App\Voucher\Infrastructure\Repository\VoucherRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - App\Voucher\Domain\Model\Voucher
        
    App\User\Domain\Repository\UserRepositoryInterface:
        class: App\User\Infrastructure\Repository\UserRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - App\User\Domain\Model\AbstractUser
        
    App\Payment\Domain\Repository\PaymentRepositoryInterface:
        class: App\Payment\Domain\Repository\PaymentRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - App\Payment\Domain\Model\Payment

