services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true
        bind:
            $commandBus: '@command.bus'
            $eventBus:   '@event.bus'
#            $now:        '@DateTimeImmutable'

    App\:
        resource: '../src/**/*'
        exclude:
            - '../src/**/*/{*Controller.php,DependencyInjection,Model,Resources,Kernel.php}'
            - '../src/Core/*'
            - '../src/**/*/{Handler}'

    infrastructure:
        namespace: App\Core\Infrastructure\
        resource: '%kernel.project_dir%/src/Core/Infrastructure/**/*'
        exclude:
            - '%kernel.project_dir%/src/Core/Infrastructure/Doctrine/*'
            - '%kernel.project_dir%/src/Core/Infrastructure/Bridge/*'
            - '%kernel.project_dir%/src/Core/Infrastructure/ApiPlatform/*'
            - '%kernel.project_dir%/src/Core/Infrastructure/EventStore/*'
            - '%kernel.project_dir%/src/Core/Infrastructure/Projection/*'

    command_handlers:
        namespace: App\
        resource: '%kernel.project_dir%/src/**/*/{*Handler.php}'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    App\Core\Domain\Saga\VoucherProcessManager:
        tags:
            - { name: messenger.message_handler, bus: event.bus, handles: App\Core\Domain\Event\OrderForVoucherPlaced }
            - { name: messenger.message_handler, bus: event.bus, handles: App\Core\Domain\Event\PaymentWasRejected }
            - { name: messenger.message_handler, bus: event.bus, handles: App\Core\Domain\Event\PaymentWasPaid }

    DateTimeImmutable:
        class: \DateTimeImmutable
        
    App\Voucher\Domain\Repository\VoucherRepositoryInterface:   '@App\Voucher\Infrastructure\Repository\VoucherRepository'
    App\User\Domain\Repository\UserRepositoryInterface:         '@App\User\Infrastructure\Repository\UserRepository'
    App\Payment\Domain\Repository\PaymentRepositoryInterface:   '@App\Payment\Infrastructure\Repository\PaymentRepository'
    App\Order\Domain\Repository\OrderRepositoryInterface:       '@App\Order\Infrastructure\Repository\OrderRepository'
